apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crm-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: crm.localdev.me
    http:
      paths:
      - backend:
          service:
            name: frontend-service
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}