apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql_secret.data.MYSQL_ROOT_PASSWORD }}
  MYSQL_USER: {{ .Values.mysql_secret.data.MYSQL_USER }}
  MYSQL_PASSWORD: {{ .Values.mysql_secret.data.MYSQL_PASSWORD }}